export const SEARCH_SUCCESS_ARTISTS = 'SEARCH_SUCCESS_ARTISTS';
export const SEARCH_FAILURE_ARTISTS = 'SEARCH_FAILURE_ARTISTS';
export const SEARCH_START_ARTISTS ='SEARCH_START_ARTISTS'

export const SEARCH_START_TRACKS ='SEARCH_START_TRACKS'
export const SEARCH_SUCCESS_TRACKS = 'SEARCH_SUCCESS_TRACKS';
export const SEARCH_FAILURE_TRACKS = 'SEARCH_FAILURE_TRACKS';

export const ADD_SEARCH_INPUT = 'ADD_SEARCH_INPUT';
export const ADD_ARTISTS_DATA = 'ADD_ARTISTS_DATA';
